# Site settings
title: "Daniel Wysocki"
email: dwysocki@oswego.edu
description: >
  This is Daniel Wysocki's home page.
url: "http://dwysocki.github.io/"
github_username: dwysocki

# Build settings
markdown: kramdown

exclude: [ "_site" ]